version: "3.7"
services:

  postgres:
    image: postgres:12.1-alpine
    volumes:
      - ./docker/postgres/init_testing_db.sql:/docker-entrypoint-initdb.d/init_testing_db.sql
    ports:
       - 5432:5432
    environment:
      POSTGRES_USER: rest-api
      POSTGRES_PASSWORD: rest-api
      POSTGRES_DB: rest-api

  php-fpm:
    build: ./docker/php
    restart: always
    volumes:
      - ../:/var/www
    working_dir: /var/www

  nginx:
    image: nginx:1.17.7-alpine
    ports:
        - 80:80
    restart: always
    volumes:
      - ../:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - postgres